---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ds-pipeline-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"   
spec:
  selector: {}
  template:
    spec:
      serviceAccount: dspa-setup
      serviceAccountName: dspa-setup
      containers:
        - name: create-ds-pipeline-config
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash" ]
          args:
            - -ec
            - |-
              echo -n 'Waiting for dsp route'
              while ! oc get route ds-pipeline-pipelines-definition 2>/dev/null | grep -qF ds-pipeline-pipelines-definition; do
                echo -n .
                sleep 5
              done; echo

              DSPPD_HOST=$(oc get route ds-pipeline-pipelines-definition -n object-detection-yolov5 -o template --template '{{.spec.host}}')
              DASHBOARD_HOST=${DSPPD_HOST/ds-pipeline-pipelines-definition-object-detection-yolov5/rhods-dashboard-redhat-ods-applications}
              ODH_DSP_JSON="{\"display_name\":\"Data Science Pipeline\",\"metadata\":{\"tags\":[],\"display_name\":\"Data Science Pipeline\",\"engine\":\"Tekton\",\"auth_type\":\"KUBERNETES_SERVICE_ACCOUNT_TOKEN\",\"api_endpoint\":\"https://${DSPPD_HOST}\",\"public_api_endpoint\":\"https://${DASHBOARD_HOST}/pipelineRuns/object-detection-yolov5/pipelineRun/view/\",\"cos_auth_type\":\"KUBERNETES_SECRET\",\"cos_secret\":\"aws-connection-pipeline-artifacts\",\"cos_endpoint\":\"http://minio.object-detection-yolov5.svc.cluster.local:9000\",\"cos_bucket\":\"pipeline-artifacts\",\"cos_username\":\"minioadmin\",\"cos_password\":\"minioadmin\",\"runtime_type\":\"KUBEFLOW_PIPELINES\"},\"schema_name\":\"kfp\"}"

              cat << EOF | oc apply -f-
              kind: Secret
              apiVersion: v1
              metadata:
                name: ds-pipeline-config
              stringData:
                odh_dsp.json: >-
                  ${ODH_DSP_JSON}
              type: Opaque
              EOF
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dspa-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dspa-setup-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: dspa-setup

