apiVersion: v1
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Pipeline Artifacts
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  name: aws-connection-pipeline-artifacts
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: pipeline-artifacts
  AWS_S3_ENDPOINT: http://minio:9000
type: Opaque
