apiVersion: v1
kind: Pod
metadata:
  name: project-check
spec:
  containers:
  - name: check
    image: busybox
    command: ['sh', '-c', 'if [ -z "$(cat /tmp/project-name)" ]; then exit 1; fi']
    volumeMounts:
    - name: config
      mountPath: /tmp
  volumes:
  - name: config
    configMap:
      name: project-name
      items:
      - key: PROJECT_NAME
        path: project-name
