apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: object-detection-yolov5
    argocd.argoproj.io/sync-wave: "1"    
  labels:
    opendatahub.io/dashboard: "true"
  name: object-detection-yolov5-pvc
  namespace: object-detection-yolov5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp3-csi
