apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    manifestival: new
  labels:
    app: ds-pipeline-pipelines-definition
    component: data-science-pipelines
  name: ds-pipeline-user-access-pipelines-definition
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
